name: GitHub Actions Demo
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Display Event Info
      run: echo "Triggered by a ${{ github.event_name }} event"

    - name: List Repository Files
      run: ls ${{ github.workspace }}

    - name: Job Completion Status
      run: echo "This job's status is ${{ job.status }}"
